/**
 * build-sprites.mjs — pack the 52 sweater/patch card faces into one CSS sprite sheet and emit the
 * matching SCSS. Re-runnable: if the art is ever revised, drop the new files in ART_DIR and re-run.
 *
 *   node scripts/build-sprites.mjs        (or: npm run build:sprites)
 *
 * Inputs : the publisher PNGs (750x1125) in ART_DIR. The card->file map below was transcribed by
 *          reading each card's printed face and cross-checked against Material::FACES (icon+slot).
 * Outputs: img/sweaters.jpg            — 4 rows (green/red/yellow/purple) x 13 cols (value 0..12; 0=patch)
 *          img/card-back.jpg           — the shared back (all sweaters + patches)
 *          src/scss/_sweater-sprites.scss — GENERATED .ucs-face-<color>_<value> position classes
 */
import sharp from 'sharp';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { writeFileSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = join(__dirname, '..');
const ART_DIR = 'C:/Users/Will/Desktop/Programming/BGA/UglyChristmasSweater/ArtFiles/PANDA PDF/Jpeg';

// --- Bleed trim -----------------------------------------------------------------------------------
// The publisher PNGs are 750x1125 = a 675x1050 bridge card (2.25"x3.5") + a uniform ~37.5px (3mm@300dpi)
// print bleed. The decorative frame sits a symmetric ~78px in on every side (measured, analyze-bleed.mjs).
// Trimming the bleed makes the sweater art reach the card edge (matching the physical cut cards) and
// leaves an even frame border. Result is the true 0.643 card ratio (NOT 2:3).
const TRIM = { left: 37, top: 37, width: 675, height: 1050 };

// --- Grid / cell geometry -------------------------------------------------------------------------
// Cards render at most ~96px wide (the popin); a 240-wide cell is retina-crisp at every size.
const CELL_W = 240;
const CELL_H = Math.round(CELL_W * TRIM.height / TRIM.width); // 373 — keep the trimmed 0.643 ratio
const COLORS = ['green', 'red', 'yellow', 'purple']; // row order
const COLS = 13;                 // value 0..12 (0 = patch)
const ROWS = COLORS.length;

// --- Card -> source-file naming -------------------------------------------------------------------
// The source art was renamed to systematic names (scripts/rename-art.mjs), so the file for each face
// is computed, not looked up: value 0 = the colour's Patch card, 1..12 zero-padded. The card->art
// decode itself was cross-checked against Material::FACES (icon+slot) when the map was first built.
const faceSrc = (color, v) => `sweater-${color}-${v === 0 ? 'patch' : String(v).padStart(2, '0')}`;
const BACK_SRC = 'sweater-back';

const src = (base) => join(ART_DIR, `${base}.png`);
const cell = (base) => sharp(src(base)).extract(TRIM).resize(CELL_W, CELL_H, { fit: 'fill' })
    .flatten({ background: '#ffffff' }).toBuffer();

async function main() {
    // ---- Compose the sprite sheet ----
    const composites = [];
    for (let r = 0; r < ROWS; r++) {
        const color = COLORS[r];
        for (let v = 0; v < COLS; v++) {
            composites.push({ input: await cell(faceSrc(color, v)), left: v * CELL_W, top: r * CELL_H });
        }
    }
    await sharp({ create: { width: COLS * CELL_W, height: ROWS * CELL_H, channels: 3, background: '#ffffff' } })
        .composite(composites)
        .jpeg({ quality: 82, mozjpeg: true })
        .toFile(join(REPO, 'img', 'sweaters.jpg'));

    // ---- The shared card back (its own file; used at many sizes via background:cover) ----
    await sharp(src(BACK_SRC)).extract(TRIM).resize(CELL_W, CELL_H, { fit: 'fill' })
        .flatten({ background: '#ffffff' }).jpeg({ quality: 82, mozjpeg: true })
        .toFile(join(REPO, 'img', 'card-back.jpg'));

    // ---- Emit the SCSS partial ----
    let scss = `// GENERATED by scripts/build-sprites.mjs — do not edit by hand.\n`
        + `// One class per sweater/patch face; keyed "<color>_<value>" (value 0 = patch), matching\n`
        + `// the client's faceOf() key (card.type + '_' + card.type_arg).\n\n`
        + `.ucs-face {\n`
        + `    background-image: url(img/sweaters.jpg);\n`
        + `    background-size: calc(var(--ucs-card-w) * ${COLS}) calc(var(--ucs-card-h) * ${ROWS});\n`
        + `    background-repeat: no-repeat;\n`
        + `}\n\n`;
    for (let r = 0; r < ROWS; r++) {
        const color = COLORS[r];
        for (let v = 0; v < COLS; v++) {
            scss += `.ucs-face-${color}_${v} { background-position: calc(var(--ucs-card-w) * ${-v}) calc(var(--ucs-card-h) * ${-r}); }\n`;
        }
    }
    writeFileSync(join(REPO, 'src', 'scss', '_sweater-sprites.scss'), scss);

    console.log(`Wrote img/sweaters.jpg (${COLS * CELL_W}x${ROWS * CELL_H}), img/card-back.jpg, src/scss/_sweater-sprites.scss`);
}

main().catch((e) => { console.error(e); process.exit(1); });
